-- Migration V2: Core Modules Schema & Seed Data (Auth, Document Library, Interactions)

-- 1. Table: users
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(50) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(150) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    unit VARCHAR(255),
    avatar_url VARCHAR(500),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Table: refresh_tokens
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token ON refresh_tokens(token);

-- 3. Table: chapters
CREATE TABLE IF NOT EXISTS chapters (
    id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    "order" INT NOT NULL DEFAULT 1,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Table: lessons
CREATE TABLE IF NOT EXISTS lessons (
    id VARCHAR(50) PRIMARY KEY,
    chapter_id VARCHAR(50) NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    "order" INT NOT NULL DEFAULT 1,
    read_time VARCHAR(50) DEFAULT '5 phút',
    created_by VARCHAR(50) REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_lessons_chapter_id ON lessons(chapter_id);

-- 5. Table: lesson_contents (8 Khối nội dung học thuật CAND lưu trữ JSONB)
CREATE TABLE IF NOT EXISTS lesson_contents (
    lesson_id VARCHAR(50) PRIMARY KEY REFERENCES lessons(id) ON DELETE CASCADE,
    objectives JSONB DEFAULT '[]'::jsonb,
    core_knowledge JSONB DEFAULT '[]'::jsonb,
    definitions JSONB DEFAULT '[]'::jsonb,
    keywords JSONB DEFAULT '[]'::jsonb,
    comparisons JSONB DEFAULT '[]'::jsonb,
    exam_hotspots JSONB DEFAULT '[]'::jsonb,
    common_traps JSONB DEFAULT '[]'::jsonb,
    memory_tips JSONB DEFAULT '[]'::jsonb
);

-- 6. Table: user_annotations
CREATE TABLE IF NOT EXISTS user_annotations (
    id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lesson_id VARCHAR(50) NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    selected_text TEXT NOT NULL,
    kind VARCHAR(50) NOT NULL,
    color VARCHAR(50) NOT NULL,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_annotations_user_lesson ON user_annotations(user_id, lesson_id);

-- 7. Table: user_lesson_progress
CREATE TABLE IF NOT EXISTS user_lesson_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lesson_id VARCHAR(50) NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    is_completed BOOLEAN DEFAULT FALSE,
    last_read_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_lesson UNIQUE(user_id, lesson_id)
);

-- SEED DATA

-- 1. Tạo tài khoản Admin mặc định (mật khẩu: admin123)
INSERT INTO users (id, email, password_hash, name, role, unit, is_active, created_at, updated_at)
VALUES (
    'usr-admin-001',
    'admin@gmail.com',
    '$2a$10$wN9XG8z2yX8z2yX8z2yX8eX8z2yX8z2yX8z2yX8z2yX8z2yX8z2y',
    'Quản Trị Viên CAND',
    'ADMIN',
    'Cục Đào tạo - Bộ Công An',
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
) ON CONFLICT (email) DO NOTHING;

-- 2. Khởi tạo 3 chương giáo trình mẫu
INSERT INTO chapters (id, title, "order", description, created_at, updated_at) VALUES
('ch-1', 'CHƯƠNG 1: NGUỒN GỐC, BẢN CHẤT VÀ CHỨC NĂNG CỦA NHÀ NƯỚC', 1, 'Lý luận chung về Nhà nước', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ch-2', 'CHƯƠNG 2: KIỂU VÀ HÌNH THỨC NHÀ NƯỚC', 2, 'Hình thái kinh tế xã hội và hình thức Nhà nước', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ch-3', 'CHƯƠNG 3: BỘ MÁY NHÀ NƯỚC CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM', 3, 'Cơ cấu tổ chức bộ máy nhà nước', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

-- 3. Khởi tạo bài học mẫu
INSERT INTO lessons (id, chapter_id, title, "order", read_time, created_at, updated_at) VALUES
('lesson-1-1', 'ch-1', 'Bài 1: Nguồn gốc ra đời của Nhà nước theo quan điểm Mác - Lênin', 1, '8 phút', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

-- 4. Khởi tạo nội dung 8 khối học thuật cho bài học mẫu
INSERT INTO lesson_contents (lesson_id, objectives, core_knowledge, definitions, keywords, comparisons, exam_hotspots, common_traps, memory_tips)
VALUES (
    'lesson-1-1',
    '["Nắm vững bản chất giai cấp và chức năng xã hội của Nhà nước & Pháp luật", "Phân tích 3 lần phân công lao động xã hội lớn dẫn tới sự tan rã công xã thị tộc", "Vận dụng quan điểm Mác - Lênin vào công tác đấu tranh phòng chống tội phạm CAND"]'::jsonb,
    '["Nhà nước là tổ chức quyền lực chính trị đặc biệt của xã hội có giai cấp, có bộ máy chuyên chế duy trì trật tự.", "Nguyên nhân kinh tế sâu xa là sự xuất hiện chế độ tư hữu và phân hóa tài sản.", "Nguyên nhân xã hội trực tiếp là mâu thuẫn giai cấp đối kháng không thể điều hòa.", "Quy phạm pháp luật là quy tắc xử sự chung do Nhà nước ban hành và bảo đảm thực hiện."]'::jsonb,
    '[{"term": "Quy phạm pháp luật", "meaning": "Quy tắc xử sự chung mang tính bắt buộc, do cơ quan nhà nước có thẩm quyền ban hành hoặc thừa nhận."}, {"term": "Chế độ tư hữu", "meaning": "Cơ sở kinh tế trực tiếp dẫn đến sự phân hóa giàu nghèo và hình thành các giai cấp đối kháng."}]'::jsonb,
    '["Quy phạm pháp luật", "Chế độ tư hữu", "Đấu tranh giai cấp", "Quyền lực nhà nước", "CAND"]'::jsonb,
    '[{"criteria": "Nguồn gốc hình thành quyền lực", "itemA": "Xuất phát từ cộng đồng thị tộc, dựa trên uy tín tự nhiên của người đứng đầu", "itemB": "Xuất phát từ giai cấp thống trị, dựa trên bộ máy cưỡng chế chuyên nghiệp của Nhà nước"}]'::jsonb,
    '["Trọng tâm câu hỏi trắc nghiệm: Nguyên nhân kinh tế sâu xa ra đời Nhà nước là gì? (Đáp án: Chế độ tư hữu)", "Cấu trúc quy phạm pháp luật gồm những bộ phận nào? (Giả định - Quy định - Chế tài)"]'::jsonb,
    '["Dễ nhầm lẫn: Nhầm đấu tranh giai cấp là nguyên nhân kinh tế (Thực chất: Đấu tranh giai cấp là nguyên nhân xã hội).", "Bẫy đề thi: Cho rằng Nhà nước xuất hiện ngay từ khi loài người mới hình thành (Sai: Xã hội công xã nguyên thủy chưa có Nhà nước)."]'::jsonb,
    '["\"Kinh tế sinh Tư hữu - Xã hội sinh Giai cấp -> Mâu thuẫn không điều hòa thì Nhà nước sinh ra.\""]'::jsonb
) ON CONFLICT (lesson_id) DO NOTHING;
